# docker-compose.yml
services:
    api:
        container_name: "auth-server-api"
        image: mozzo/auth-server:1.0.0
        volumes:
            - auth_db_vol:/app/instance
        env_file:
            - .env
        ports:
            - 5001:5000

volumes:
    auth_db_vol: