# docker-compose.yml
services:
    db:
        container_name: "auth-server-db"
        image: "postgres" # use latest official postgres version
        ports:
            - 5433:5432
        restart: always
        env_file:
            - .env
        volumes:
            - auth-server:/var/lib/postgresql/db-data/ # persist data even if container shuts down
    api:
        container_name: "auth-server-api"
        build: .
        image: auth-server-api
        depends_on:
            - "db"
        env_file:
            - .env
        ports:
            - 5001:5000
volumes:
    auth-server: