# docker-compose.yml
services:
    api:
        container_name: "auth-server-api"
        build: .
        image: auth-server-api
        env_file:
            - .env
        ports:
            - 5001:5000
